---
abstract: 'Handle combination loading and processing of on-disk resources.'
author:
  - 'J. Shirley <j@shirley.im>'
build_requires:
  HTTP::Request::Common: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ComboLoader
requires:
  Carp: 0
  HTTP::Date: 0
  HTTP::Throwable: 0
  HTTP::Throwable::Factory: 0
  Path::Class: 0
  Plack: 0
  Plack::MIME: 0
  Plack::Middleware: 0
  Plack::Request: 0
  Try::Tiny: 0
  URI::Escape: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/jshirley/Plack-Middleware-ComboLoader
  repository: https://github.com/jshirley/Plack-Middleware-ComboLoader.git
version: 0.02
